### MySQL Configuration for Development Profile
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/miniprojectdb
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#---
## Hibernate Configuration
#  jpa:
#    hibernate:
#      ddl-auto: create
#      dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#
## Logging Configuration
#  logging:
#    level:
#      org.springframework: INFO
#
## Server Configuration
#  server:
#    port: 8080
